# Generated by Django 6.0.7 on 2026-07-19 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('best_season', models.CharField(blank=True, max_length=100)),
                ('main_category', models.CharField(choices=[('natural', 'Natural Attractions'), ('village_rural', 'Village & Rural Tourism'), ('cultural_religious', 'Cultural & Religious Sites'), ('urban_modern', 'Urban & Modern Attractions'), ('trekking_adventure', 'Trekking & Adventure'), ('wildlife_conservation', 'Wildlife & Conservation'), ('wellness_relaxation', 'Wellness & Relaxation')], max_length=30)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('activities', models.CharField(blank=True, max_length=300)),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('hard', 'Hard'), ('very_hard', 'Very Hard')], max_length=15)),
                ('accessibility', models.CharField(blank=True, max_length=200)),
                ('transportation', models.TextField(blank=True)),
                ('crowd_level', models.CharField(choices=[('very_low', 'Very Low'), ('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('very_high', 'Very High')], max_length=10)),
                ('budget_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('visit_duration_days', models.FloatField(default=0.25)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('ratings', models.FloatField(blank=True, null=True)),
                ('popularity', models.FloatField(blank=True, null=True)),
                ('attraction_total_reviews', models.PositiveIntegerField(default=0)),
                ('is_trek_entry', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='destinations.destination')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrekRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('total_days', models.PositiveIntegerField()),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('hard', 'Hard'), ('very_hard', 'Very Hard')], max_length=15)),
                ('description', models.TextField(blank=True)),
                ('entry_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_starting_here', to='destinations.destination')),
                ('exit_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_ending_here', to='destinations.destination')),
            ],
        ),
        migrations.CreateModel(
            name='RouteStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField(blank=True)),
                ('overnight_stop', models.BooleanField(default=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='destinations.trekroute')),
            ],
            options={
                'ordering': ['route', 'day_number'],
            },
        ),
    ]
