# Generated by Django 5.2 on 2026-08-08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destinations", "0003_alter_destination_image_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="DestinationView",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                ("destination", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="detail_views", to="destinations.destination")),
            ],
            options={"ordering": ["-viewed_at"]},
        ),
    ]
