import { useEffect, useMemo, useState } from "react";
import { MessageSquareText, Search, Star, Trash2 } from "lucide-react";
import { adminService, type AdminReview } from "@/services/adminService";
import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/Input";

export default function ReviewManagementPage() {
  const [reviews, setReviews] = useState<AdminReview[]>([]); const [query, setQuery] = useState(""); const [rating, setRating] = useState(""); const [error, setError] = useState("");
  useEffect(() => { adminService.reviews().then(setReviews).catch(() => setError("Unable to load reviews.")); }, []);
  const shown = useMemo(() => reviews.filter((review) => `${review.user_name} ${review.user_email} ${review.destination_name} ${review.comment}`.toLowerCase().includes(query.toLowerCase()) && (!rating || String(review.rating) === rating)), [reviews, query, rating]);
  const remove = async (review: AdminReview) => { if (!confirm(`Remove this review from ${review.destination_name}?`)) return; try { await adminService.deleteReview(review.id); setReviews((all) => all.filter((item) => item.id !== review.id)); } catch { setError("Could not remove this review."); } };
  return <div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold text-primary">MODERATION</p><h1 className="mt-1 text-3xl font-bold">Review management</h1><p className="mt-2 text-muted-foreground">Review traveller feedback and remove inappropriate content.</p></div><span className="rounded-full bg-light-blue px-3 py-1 text-sm font-semibold text-primary">{shown.length} reviews</span></div><section className="mt-7 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:p-6"><div className="flex flex-col gap-3 sm:flex-row"><div className="flex h-11 flex-1 items-center gap-3 rounded-xl border border-input px-3"><Search className="size-5 shrink-0 text-muted-foreground" /><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search traveller, destination, or review" className="h-9 border-0 px-0 shadow-none focus-visible:ring-0" /></div><select value={rating} onChange={(event) => setRating(event.target.value)} className="h-11 rounded-xl border border-input bg-white px-3 sm:w-44"><option value="">All ratings</option>{[5, 4, 3, 2, 1].map((value) => <option key={value} value={value}>{value} star{value > 1 ? "s" : ""}</option>)}</select></div>{error && <p className="mt-4 text-sm text-red-600">{error}</p>}<div className="mt-6 grid gap-4 lg:grid-cols-2">{shown.map((review) => <article key={review.id} className="rounded-2xl border border-slate-200 p-5"><div className="flex items-start justify-between gap-3"><div className="flex min-w-0 gap-3"><span className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-light-blue text-primary"><MessageSquareText className="size-5" /></span><div className="min-w-0"><p className="truncate font-semibold">{review.user_name || "Unnamed traveller"}</p><p className="truncate text-sm text-muted-foreground">{review.user_email}</p><p className="mt-1 text-sm font-medium text-primary">{review.destination_name}</p></div></div><span className="flex shrink-0 items-center gap-1 rounded-full bg-amber-50 px-2.5 py-1 text-sm font-bold text-amber-600"><Star className="size-3 fill-current" />{review.rating}.0</span></div><p className="mt-4 min-h-12 text-sm leading-6 text-slate-600">{review.comment || "No written comment was provided."}</p><div className="mt-4 flex items-center justify-between border-t border-slate-100 pt-3"><span className="text-xs text-muted-foreground">{new Date(review.created_at).toLocaleDateString()}</span><Button variant="destructive" size="sm" onClick={() => remove(review)}><Trash2 />Remove</Button></div></article>)}</div>{!shown.length && <div className="py-14 text-center text-muted-foreground">No reviews match the selected filters.</div>}</section></div>;
}
